/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StockIndexRouteImport } from './routes/stock/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as BranchesIndexRouteImport } from './routes/branches/index'
import { Route as StockAddRouteImport } from './routes/stock/add'
import { Route as ProductsCreateRouteImport } from './routes/products/create'
import { Route as BranchesCreateRouteImport } from './routes/branches/create'
import { Route as ProductsEditIdRouteImport } from './routes/products/edit/$id'
import { Route as BranchesEditIdRouteImport } from './routes/branches/edit/$id'
import { Route as StockBranchIdProductIdSummaryRouteImport } from './routes/stock/$branchId/$productId/summary'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StockIndexRoute = StockIndexRouteImport.update({
  id: '/stock/',
  path: '/stock/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesIndexRoute = BranchesIndexRouteImport.update({
  id: '/branches/',
  path: '/branches/',
  getParentRoute: () => rootRouteImport,
} as any)
const StockAddRoute = StockAddRouteImport.update({
  id: '/stock/add',
  path: '/stock/add',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCreateRoute = ProductsCreateRouteImport.update({
  id: '/products/create',
  path: '/products/create',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesCreateRoute = BranchesCreateRouteImport.update({
  id: '/branches/create',
  path: '/branches/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsEditIdRoute = ProductsEditIdRouteImport.update({
  id: '/products/edit/$id',
  path: '/products/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesEditIdRoute = BranchesEditIdRouteImport.update({
  id: '/branches/edit/$id',
  path: '/branches/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StockBranchIdProductIdSummaryRoute =
  StockBranchIdProductIdSummaryRouteImport.update({
    id: '/stock/$branchId/$productId/summary',
    path: '/stock/$branchId/$productId/summary',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/branches/create': typeof BranchesCreateRoute
  '/products/create': typeof ProductsCreateRoute
  '/stock/add': typeof StockAddRoute
  '/branches': typeof BranchesIndexRoute
  '/products': typeof ProductsIndexRoute
  '/stock': typeof StockIndexRoute
  '/branches/edit/$id': typeof BranchesEditIdRoute
  '/products/edit/$id': typeof ProductsEditIdRoute
  '/stock/$branchId/$productId/summary': typeof StockBranchIdProductIdSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/branches/create': typeof BranchesCreateRoute
  '/products/create': typeof ProductsCreateRoute
  '/stock/add': typeof StockAddRoute
  '/branches': typeof BranchesIndexRoute
  '/products': typeof ProductsIndexRoute
  '/stock': typeof StockIndexRoute
  '/branches/edit/$id': typeof BranchesEditIdRoute
  '/products/edit/$id': typeof ProductsEditIdRoute
  '/stock/$branchId/$productId/summary': typeof StockBranchIdProductIdSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRoute
  '/branches/create': typeof BranchesCreateRoute
  '/products/create': typeof ProductsCreateRoute
  '/stock/add': typeof StockAddRoute
  '/branches/': typeof BranchesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/stock/': typeof StockIndexRoute
  '/branches/edit/$id': typeof BranchesEditIdRoute
  '/products/edit/$id': typeof ProductsEditIdRoute
  '/stock/$branchId/$productId/summary': typeof StockBranchIdProductIdSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/branches/create'
    | '/products/create'
    | '/stock/add'
    | '/branches'
    | '/products'
    | '/stock'
    | '/branches/edit/$id'
    | '/products/edit/$id'
    | '/stock/$branchId/$productId/summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/branches/create'
    | '/products/create'
    | '/stock/add'
    | '/branches'
    | '/products'
    | '/stock'
    | '/branches/edit/$id'
    | '/products/edit/$id'
    | '/stock/$branchId/$productId/summary'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/branches/create'
    | '/products/create'
    | '/stock/add'
    | '/branches/'
    | '/products/'
    | '/stock/'
    | '/branches/edit/$id'
    | '/products/edit/$id'
    | '/stock/$branchId/$productId/summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRoute
  BranchesCreateRoute: typeof BranchesCreateRoute
  ProductsCreateRoute: typeof ProductsCreateRoute
  StockAddRoute: typeof StockAddRoute
  BranchesIndexRoute: typeof BranchesIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  StockIndexRoute: typeof StockIndexRoute
  BranchesEditIdRoute: typeof BranchesEditIdRoute
  ProductsEditIdRoute: typeof ProductsEditIdRoute
  StockBranchIdProductIdSummaryRoute: typeof StockBranchIdProductIdSummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/': {
      id: '/stock/'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches/': {
      id: '/branches/'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/add': {
      id: '/stock/add'
      path: '/stock/add'
      fullPath: '/stock/add'
      preLoaderRoute: typeof StockAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/create': {
      id: '/products/create'
      path: '/products/create'
      fullPath: '/products/create'
      preLoaderRoute: typeof ProductsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches/create': {
      id: '/branches/create'
      path: '/branches/create'
      fullPath: '/branches/create'
      preLoaderRoute: typeof BranchesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/edit/$id': {
      id: '/products/edit/$id'
      path: '/products/edit/$id'
      fullPath: '/products/edit/$id'
      preLoaderRoute: typeof ProductsEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches/edit/$id': {
      id: '/branches/edit/$id'
      path: '/branches/edit/$id'
      fullPath: '/branches/edit/$id'
      preLoaderRoute: typeof BranchesEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/$branchId/$productId/summary': {
      id: '/stock/$branchId/$productId/summary'
      path: '/stock/$branchId/$productId/summary'
      fullPath: '/stock/$branchId/$productId/summary'
      preLoaderRoute: typeof StockBranchIdProductIdSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRoute,
  BranchesCreateRoute: BranchesCreateRoute,
  ProductsCreateRoute: ProductsCreateRoute,
  StockAddRoute: StockAddRoute,
  BranchesIndexRoute: BranchesIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  StockIndexRoute: StockIndexRoute,
  BranchesEditIdRoute: BranchesEditIdRoute,
  ProductsEditIdRoute: ProductsEditIdRoute,
  StockBranchIdProductIdSummaryRoute: StockBranchIdProductIdSummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
